### ISSUE TITLE
optidef messes with overbrace somehow

### ISSUE THREAD

**Issue by roversch** [jeslago/optidef#17] opened 2018-07-13 10:16 UTC
The following LaTex code
```
\documentclass{article}

\usepackage{amsmath}
\usepackage{mathabx}
\usepackage{optidef}

\begin{document}

\begin{equation*}
\overbrace{T + H + I + S \times U + N + D + E + R}^{\mathrm{top}}
\end{equation*}

\end{document}
```

results in 

<img width="808" alt="screen shot 2018-07-13 at 12 13 19" src="https://user-images.githubusercontent.com/1436556/42686420-2b9b2e36-8696-11e8-9fb7-bea6b061e159.png">

If I switch the lines `\usepackage{mathabx}` and `\usepackage{optidef}`, it returns the correct overbrace rendering:

<img width="796" alt="screen shot 2018-07-13 at 12 14 28" src="https://user-images.githubusercontent.com/1436556/42686472-503e93fe-8696-11e8-97bc-d32d4adcd377.png">

Note that if I don't include `amsmath`, it does not even compile. ('command `\iint` already defined' etc). My guess is that somehow, optidef relies on `amsmath` and is unhappy with `mathabx` being included first.

**Comment by jeslago** [comment] 2018-07-13 10:21
Thanks for posting Robin! I will take a look at the clash and see how can be avoided.

**Comment by bonanza123** [comment] 2018-07-13 10:34
I guess the problem is not in `optidef` but rather the fact that `mathabx` overwrites the definition of the braces etc. A reasonable way would be to load only those glyphs form `mathabx` that you need,  via `\usepackage[ putYourClassHere ]{mathabx}`, cf. the `mathabx` documentation.

**Comment by jeslago** [comment] 2018-07-13 11:25
Thanks for that answer. I also think that might be the issue, but I would take a look to the optidef code if something can be done to improve compatibility with `mathabx`

**Comment by roversch** [comment] 2018-07-13 12:25
Thanks for the help! If `mathabx` is the problem, why does it work if you switch the statement order? I would expect it to give wrong results in both cases.

**Comment by roversch** [comment] 2018-07-13 12:34
@bonanza123 thanks for that hint by the way, but `\usepackage[mathx]{mathabx}` also overwrites `\neq`, making it unusable.

**Comment by bonanza123** [comment] 2018-07-13 12:41
There are a lot of packages where order matters (hyperref and cleveref for example). Lets ask the other way around, why do you need `mathabx` to begin with?

**Comment by roversch** [comment] 2018-07-13 12:45
Okay, good point. I need mathabx for 'widecheck'.

**Comment by bonanza123** [comment] 2018-07-13 12:48
Ahh, ok: I guess the problem with optidef is that it loads `mathtools` (which loads amsmath IMHO). 

But for you, check out this: https://tex.stackexchange.com/questions/44235/is-there-a-way-to-do-an-upside-down-widehat/44251 regarding the alternatives to `mathabx` for that glyph.

**Comment by roversch** [comment] 2018-07-13 12:50
That makes sense. Yeah, I saw that SO post before. Thanks for the clarification!

**Comment by jeslago** [comment] 2018-07-17 15:30
I am closing this issue. I will add a section in the documentation to indicate the possible issue when using `optidef` with `mathabx` and how to solve it. From my side, there is nothing I can do in the optidef package.

**Closed as completed by jeslago** 2018-07-17 15:30 UTC
