### ISSUE TITLE
An indentation after using "maxi!" is forced

### ISSUE THREAD

**Issue by ghost** [jeslago/optidef#18] opened 2018-07-24 02:03 UTC
First, thank you for creating the "optidef" package.
The bug I want to report is about indenting (although there may be a problem with my usage).

```
\begin{maxi!}|l|[3]
	{x}
	{f(x) \protect\label{Prob:Obj}}
	{\label{Prob}}
	{}
	\addConstraint{g_j(x)}{\le 0,\protect\label{Const:Comm}}{\forall j=0,\ldots,M}
	\addConstraint{h_j(x)}{= 0,\protect\label{Const:Comm}}{\forall j=0,\ldots,N,}
\end{maxi!}
where $g_j$ and $h_j$ are blah blah blah.
```

In the above code, there is an indentation before "where". I remember that in previous versions there was no bug for this indentation. How should I solve it?

**Comment by jeslago** [comment] 2018-08-07 09:23
I cannot reproduce the indentation issue. Also, it is not clear from your description where the problem is located. What do you mean before "where"? You do not use the word "where" anywhere in your optimization problem.

**Comment by ghost** [comment] 2018-08-07 09:59
I edited my question. I put the sentence including 'where blah blah blah' into the source code.
In the old version, there is no indentation. However, in the newest version, the indentation appears.
You can check my problem [here](https://tex.stackexchange.com/questions/442815/how-to-remove-the-indentation-after-the-optimization-problem).

**Comment by jeslago** [comment] 2018-08-07 12:25
Can you try the version I just committed and see if the error persist? It has been solved in my computer with the modification I made.

**Closed as completed** 2018-08-31 09:34 UTC
