### ISSUE TITLE
Error using class file of Wiley journal OCAM

### ISSUE THREAD

**Issue by mheitel** [jeslago/optidef#20] opened 2018-10-02 07:51 UTC
First of all, thank you for this great and useful LaTeX package!

I am currently writing a paper which I want to submit to the Wiley journal Optimal Control Applications and Methods (OCAM). They use a special [class file](https://onlinelibrary.wiley.com/page/journal/10991514/homepage/la_tex_class_file.htm)
It seems that using both optidef and this class file causes the following two errors while compiling:

**Argument of \env@new has an extra }. \end{document}
Paragraph ended before \env@new was complete. \end{document}**

A minimal example that produces this error is given by
```
\documentclass[AMA,STIX1COL]{WileyNJD-v2}
\usepackage{optidef}

\begin{document}
	This is some text \cite{article01}
	
	\begin{mini!}{x}{f(x)}{\label{mylabel}}{}
		\addConstraint{g(x)}{\le 0}
		\addConstraint{h(x)}{= 0}
	\end{mini!}

	\bibliographystyle{plain}
	\bibliography{miniLiterature}
\end{document}
```

where the miniLiterature.bib file is just a small bib file with 
```
@article{article01,
    author = {surname familyname},	
    title = {title},
    journal = {journal},
    year = {2000},
    volume = {volume},
    number = {number}, 
    pages = {pages}, 
    month = {month}, 
    note = {note},
}
```

**Comment by jeslago** [comment] 2018-10-02 08:10
Hi, 

could you provide the WileyNJD-v2 style?

In addition, if would recommend you not to use optidef for submitting the paper. At the moment I don't have much time for looking into the problem, so waiting for fixing the problem might delay your submission,

Cheers.

**Comment by mheitel** [comment] 2018-10-02 08:22
Yes, of course, I can. Unfortunately, GitHub does not support .cls files for attachments. Therefore, I have updated the link of my first post. It should work now. 

Thanks for your fast answer.

**Comment by jeslago** [comment] 2019-01-22 18:28
Sorry for the late reply. This bug was harder to track than usual.

I have looked into the issue and I think it is not a problem between optidef and the WileyNJD-v2 class file. Instead, it seems to be a problem between the package [environ](https://ctan.org/pkg/environ?lang=en) and the WileyNJD-v2 class file. In your example above, if you replace the line where you import optidef by the package [environ](https://ctan.org/pkg/environ?lang=en) and then define an environment, i.e.: 
```
\documentclass[AMA,STIX1COL]{WileyNJD-v2}
\usepackage{environ}
\NewEnviron{BaseMiniwe}[4]{}%

\begin{document}
	This is some text \cite{article01}
	
\bibliography{wileyNJD-AMA}%

\end{document}
```
the same issue that you mentioned pops up. As optidef relies on the package [environ](https://ctan.org/pkg/environ?lang=en) to define the environments, there is nothing much I can do to help you. Perhaps you could contact the developers of the [environ](https://ctan.org/pkg/environ?lang=en) package and ask them if they know what the issue is.

**Comment by mheitel** [comment] 2019-01-25 07:12
Thanks for your reply. I did not use optidef for the submission of my paper. Since this problem occurred only in combination with the WileyNJD-v2 class file, which I use very rarely, it seems not that important for me to solve this issue. I hoped that it would be a minor bug. Thanks for tracking the problem!

**Comment by jeslago** [comment] 2019-01-25 13:54
I am closing then this issue.

**Closed as completed by jeslago** 2019-01-25 13:54 UTC
